apiVersion: cnfw.cisco.com/v1
kind: ASAConfiguration
metadata:
  name: s2svpn-config
  namespace: sfcn-system
  labels:
    sfcn.cisco.com/service-role: "default"
spec:
  order: 3
  cliLines: |
    # 10.37.32.0 as the inside IP address of ASAc in site1
    # 10.38.32.0 as the inside IP address of ASAc in site2
    # 3.219.43.20 as the outside IP address of ASAc in site2
    crypto ikev2 policy 1
    encryption aes-256
    integrity sha256
    group 14
    prf sha256
    lifetime seconds 86400
    crypto ikev2 enable outside
    crypto ipsec ikev2 ipsec-proposal AES256
    protocol esp encryption aes-256
    protocol esp integrity sha-256
    access-list outside_cryptomap extended permit ip 10.37.32.0 255.255.240.0 10.38.32.0 255.255.240.0
    # Change to your own group tunnel name
    crypto isakmp identity key-id your-group-tunnel-name
    crypto ikev2 enable outside
    group-policy GroupPolicy_3.219.43.20 internal
    group-policy GroupPolicy_3.219.43.20 attributes
    vpn-tunnel-protocol ikev2
    tunnel-group 3.219.43.20 type ipsec-l2l
    tunnel-group 3.219.43.20 general-attributes
    default-group-policy GroupPolicy_3.219.43.20
    tunnel-group 3.219.43.20 ipsec-attributes
    ikev2 remote-authentication pre-shared-key 12345
    ikev2 local-authentication pre-shared-key 12345
    crypto map outside_map 1 match address outside_cryptomap
    crypto map outside_map 1 set peer 3.219.43.20
    crypto map outside_map 1 set ikev2 ipsec-proposal AES256
    crypto map outside_map interface outside