# us-east-1 is used here, but you don't necessarily need to replicate the files to all regions.
# S3 is just a file server in this context, so as long as you can reach it from your org
# you can have a single config for all clusters.
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: ravpnprofile
  namespace: sfcn-system 
spec:
  fileName: ravpn-profile.xml
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: ravpn-profile.xml
   auth:
     secretName: s3-auth-secret
     accessKeyField: access_key
     secretKeyField: secret_key
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectlinux
  namespace: sfcn-system 
spec:
  fileName: anyconnect-linux64-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-linux64-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: s3-auth-secret
     accessKeyField: access_key
     secretKeyField: secret_key
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectwin
  namespace: sfcn-system 
spec:
  fileName: anyconnect-win-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-win-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: s3-auth-secret
     accessKeyField: access_key
     secretKeyField: secret_key
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectmac
  namespace: sfcn-system 
spec:
  fileName: anyconnect-macos-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-macos-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: s3-auth-secret
     accessKeyField: access_key
     secretKeyField: secret_key
---
