# This secret is used to pull files from your S3 bucket.
# See FileObject samples in fileobjects-anyconnect.yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3-auth-secret
  namespace: sfcn-system
type: Opaque
data:
  # Add your user access key and secret key 
  # to the S3 bucket for AnyConnect images and RAVPN profile xml
  access_key: <your-s3-user-access-key>
  secret_key: <your-s3-user-secret-key>

