apiVersion: v1
kind: Secret
metadata:
  name: s3-auth-secret
  namespace: sfcn-system
type: Opaque
data:
  # Add your user access key and secret key which correspond to your
  # AWS credentials. This will allow you to pull files from your S3
  # bucket via the FileObject CRD.
  # Note: If your files are hosted on an http/https server, you 
  # can skip this step
  access_key: <your-s3-user-access-key>
  secret_key: <your-s3-user-secret-key>