apiVersion: v1
kind: Secret
metadata:
  name: s3filesecret
  namespace: sfcn-system
type: Opaque
data:
  # Add your user access key and secret key 
  # to the S3 bucket for AnyConnect images and RAVPN profile xml
  access_key: <your-s3-user-access-key>
  secret_key: <your-s3-user-secret-key>
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectlinux
  namespace: sfcn-system 
spec:
  fileName: anyconnect-linux64-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-linux64-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: "s3filesecret"
     accessKeyField: "access_key"
     secretKeyField: "secret_key"
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectwin
  namespace: sfcn-system 
spec:
  fileName: anyconnect-win-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-win-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: "s3filesecret"
     accessKeyField: "access_key"
     secretKeyField: "secret_key"
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: anyconnectmac
  namespace: sfcn-system 
spec:
  fileName: anyconnect-macos-4.9.05042-webdeploy-k9.pkg
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: anyconnect-macos-4.9.05042-webdeploy-k9.pkg
   auth:
     secretName: "s3filesecret"
     accessKeyField: "access_key"
     secretKeyField: "secret_key"
---
apiVersion: cnfw.cisco.com/v1
kind: FileObject
metadata:
  name: ravpnprofile
  namespace: sfcn-system 
spec:
  fileName: ravpn-profile.xml
  s3:
   bucket: sfcn-s3-bucket
   region: us-east-1
   item: ravpn-profile.xml
   auth:
     secretName: "s3filesecret"
     accessKeyField: "access_key"
     secretKeyField: "secret_key"
---
# This certificate is provided by you. It is a PKCS12 formatted cert
# generated on the domains used in your Route53Ingress config. 
# For VPN Redirector topology, this should be a wildcard cert which 
# covers the parent and subdomains used for VPN. 
# 
# Example: if using "domain.com" as the parent domain, with 
# "us.domain.com" and "eu.domain.com" as subdomains, your wildcard
# should include "*.domain.com", "*.us.domain.com", and "*.eu.domain.com"
# 
apiVersion: v1
kind: Secret
metadata:
  name: mypkcs
  namespace: sfcn-system
stringData:
  trustpoint: ssltp
  password: test
  value: |
    MIIS2gIBAzCCEqAGCSqGSIb3DQEHAaCCEpEEghKNMIISiTCCDQcGCSqGSIb3DQEH
    BqCCDPgwggz0AgEAMIIM7QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIh63X
    549tUD0CAggAgIIMwHVhJkKRWCORnqaj4ixxBJL80fmIH327kRtftzBY59Rjz93s
    ZwNibpOx2/UadS+LYaB9G9+ZfK38fxyRkPIejME1BEQXhok3uhlijFqaoCpAY5xz
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    EZF8S6wcSGkeu7444GAVfcQjiPH54T5QEST07GlGlQjObO6K4CtC2E9YQPFOyGFs
    <shortened for brevity>
    MRpjKvfSuc8qmM5TPxnLJwQILJ/u4ij4txACAggA
---
apiVersion: cnfw.cisco.com/v1
kind: Route53Ingress
metadata:
  name: vpn
  namespace: sfcn-system
spec:
  # Change to your Route53 hosted zone
  hostedZone: Z056XXXXXXXXXXXXXE0EK
  # Change to your VPN domain name
  recordSetName: vpn.domain.com
---
apiVersion: v1
kind: Secret
metadata:
  name: userinfo 
  namespace: sfcn-system
stringData:
  # RA VPN client details
  username: jsmith
  password: cisco123
  privilege: "15"
---
apiVersion: cnfw.cisco.com/v1
kind: IPv4SubnetPool
metadata:
  name: ravpnpool
  namespace: sfcn-system 
  annotations:
    # enables AWS Route Table integration for this pool
    aws.cnfw.cisco.com/type: "route-table"
    # EP's node interface index that will be used as route target
    aws.cnfw.cisco.com/interface-index: "3"
    # AWS Route Table ID that will be synced with assigned subnets.
    # This should be the table that includes your outside and inside networks, usually named "Inside Subnets"
    aws.cnfw.cisco.com/route-table-id: <your_public_route_table_id>
spec:
  address: "10.10.0.0"
  supernetPrefix: 16
  subnetPrefix: 24
---
apiVersion: cnfw.cisco.com/v1
kind: ASAConfiguration
metadata:
  name: ravpnconfig
  namespace: sfcn-system 
  labels:
    sfcn.cisco.com/service-role: "default"
spec:
  order: 1
  description: "ravpnconfig"
  secrets:
    - "mypkcs"
    - "userinfo"
  fileObjects:
    - "ravpnprofile"
    - "anyconnectlinux"
    - "anyconnectwin"
    - "anyconnectmac"
  ipv4SubnetPools:
    - "ravpnpool"
  cliLines: |
    interface Management0/0
      no management-only
      nameif management
      security-level 0
      ip address dhcp 
    interface TenGigabitEthernet0/0
      nameif outside
      security-level 0
      ip address dhcp
    interface TenGigabitEthernet0/1
      nameif inside
      security-level 100
      ip address dhcp 
    route outside 0.0.0.0 0.0.0.0 {{ index .nodeLabels "sfcn.cisco.com.interface.2/gateway-ipv4" }} 1
    route inside 10.37.0.0 255.255.0.0 {{ index .nodeLabels "sfcn.cisco.com.interface.3/gateway-ipv4" }} 2 
    ip local pool AC_Pool {{.ipv4SubnetPools.ravpnpool.assignedRange}} mask 255.255.255.0
    access-list Split_Tunnel_ACL standard permit 10.37.0.0 255.255.0.0
    aaa authentication http console LOCAL
    webvpn
      enable outside
      anyconnect profiles AC_Client_Profile {{ .fileObjects.ravpnprofile.path }}
      anyconnect image {{ .fileObjects.anyconnectlinux.path }} 1
      anyconnect image {{ .fileObjects.anyconnectwin.path }} 2
      anyconnect image {{ .fileObjects.anyconnectmac.path }} 3
      anyconnect enable
      tunnel-group-list enable
      cache
        disable
    group-policy GroupPolicy_AC_Profile internal
    group-policy GroupPolicy_AC_Profile attributes
      vpn-tunnel-protocol ssl-client
      split-tunnel-policy tunnelspecified
      split-tunnel-network-list value Split_Tunnel_ACL
      default-domain none
      vpn-idle-timeout none
      vpn-session-timeout none
      webvpn
        anyconnect profiles value AC_Client_Profile type user
    dynamic-access-policy-record DfltAccessPolicy
    username {{ .secrets.userinfo.username }} password {{ .secrets.userinfo.password }} privilege 15
    tunnel-group AC_Profile type remote-access
    tunnel-group AC_Profile general-attributes
      address-pool AC_Pool
      default-group-policy GroupPolicy_AC_Profile
    tunnel-group AC_Profile webvpn-attributes
      group-alias Anyconnect enable
    crypto ca import {{ .secrets.mypkcs.trustpoint }} pkcs12 {{ .secrets.mypkcs.password }} nointeractive
    {{ .secrets.mypkcs.value }}
    quit
    ssl trust-point {{ .secrets.mypkcs.trustpoint }}
