# This certificate is provided by you. It is a PKCS12 formatted cert
# generated on the domains used in your Route53Ingress config. 
# For VPN Redirector topology, this should be a wildcard cert which 
# covers the parent and subdomains used for VPN. 
# 
# Example: if using "domain.com" as the parent domain, with 
# "us.domain.com" and "eu.domain.com" as subdomains, your wildcard
# should include "*.domain.com", "*.us.domain.com", and "*.eu.domain.com"
# 
apiVersion: v1
kind: Secret
metadata:
  name: mypkcs
  namespace: sfcn-system
stringData:
  trustpoint: ssltp
  password: test
  format: pkcs12
  value: |
    MIISTAIBAzCCEhIGCSqGSIb3DQEHAaCCEgMEghH/MIIR+zCCDIcGCSqGSIb3DQEH
    BqCCDHgwggx0AgEAMIIMbQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIAnO7    
    pDQB6EkCAggAgIIMQCYebZ+8LTkQFLQEZkNOUR9TfWJM9nirq9NQX0pWm/vJIGdZ
    4uX4jGB6zqVB5cTljkCS36kSrjT9pDDU1JlmZ26dpjqnr50g0ZfUDV8Of3YfA+8e
    6Z3VnE6hhiMjJ6G89RWGfljME4tAy6lJ1wcVNOpu7Qv/V2NH+uVpA02kXu5zmyhL
    TnKAjV31+K3ZXEb7/vtFRugD7rHCcwCsHUizFGZfcXBFBKNSnx8hBDcFS7/LvTe6
    c7wvYPQI86NQf0E8oYpss3sOGspcKubNYQAYaIM2Dmqu+ljkDkWKxaxg+43XuoQq
    03YFZd7b64xXQf9JoVhPfiJJUpb+9a6ZbFdxZdi3VYu5Cymoo4oj7c0HPP83W2sn
    pqVGcaUrHOKvcm1Cytv3Gswxsb4FaRvOjhJIMdELP+sIcGefV7Zjpy3Gn6o9n2WY
    QVVWSMhj9eRcrcn15joj5WIf4JLLu4AwrHDm0ArjnAn565OF3MhcpHON8mHwTOHP
    fh1dC4RB2jvCsi7roD+two6N7dSG2mDqUtCD71T50bcF27f8Rf7jh1r3sPlgFARX
    jSaGUB+odGPS3ieAnGqSL3epU4wCxZ7SBRK3jXDxHyuUHxv1wmcrwOUsYeAk6Tg2
    6ZC17VGS/pDB0c4RC2JgJ/UJR/bRpWCTKmijflFGXpYAssAS7MUtwQaDxliorv4q
    NaNc+WLvSXJSaOZ/zOhpx4Sqs7KCOFseuMvapWWPo/1CpJsc67XsrkAhSwd0Ovyf
    jH3q34KSp2EODCAYzywga8IDdgCO5EM6YHOcwgkmlpIWvL/gq1Gh0NrAhlVOurKO
    DYyFJgHhkTlVeDvZbZ1YNuvz7V8Pl03+TgX093bYEBptqcBzv9sWyxRKMOCe6SVC
    w0gUKSSo0FsWeeT+Dj71ZHyF3/OPPCNGRMgMZ5bpdIYVrp1XoajSX76HOQ4FOSos
    O3gKHC0STrXJGB+isAuylvJnXvworbIyfzLSdNzImogrQagslheCuMHKnRjGQyc9
    1SyjA4UZDRRiKJJjuAHWu2c6YpYMl5nMdk3sxIXHR2Nm1kV0IepmCc+qRj5lEUyw
    XACsmxLsp6no1ePD14RPBjqOSz/fvJGqArMrNDQNv0JOOdHObGTfpC1kMN9Zgzz5
    wSZcxDFZkS5a7RCg+uG85On1dHDb/nMz5fZ1bDTh5z7jxpBaYYtKBkK0upqsc/Bv
    /IvEcmv2hhFXeQpI1T/2L1fMCbAorD2oCuOvwkTWxSvHfoKlvB9FtJbWl+uDG1xn
    7L+nrUWBJ07TXiJRiaUUpUH8Wi1ZqQB+s8xZAjMCR6SN5d2g10ftEYiU5PZAGlBm
    exL2zGc07m/l7RVY9sSCSeiIKFImCg/sDmMkiVp7hMymeSXXNGZlJgAJlrs0RZFj
    os/7DB5FK/U8/mTC/vGenzTAaWjfzCpUX7iq2GXYaHaoehylWiTzLSPXmykHVGm5
    3uMrB4bEkzj0R/DUrL0wzU89oBgdo9K4y8ojSGXstAh2/T7jVHfWxxDLWriXlXR1
    BlSnaJpCQ5ExfWrhq1EgOivXZ0GHYwdcC24OzqeTNwzgZMFU3UfFdikKHZk/dviO
    9rbiqE+w92hvqAdEEju9oZRphEykgXUZyBSs1d7PzaXGnnbPhPCMDEox8HoXaA2r
    dIXGB+GBt24iw/ML595GcfLWA2Xolv+LLpPwxz/X/bJ1cDROrsPxjAjZWThIUO1n
    DoWiFS44B/jB76RsiELtAhrANy2+bVqLr9olVdlJG4Xr+OWbNq/iCWqeGV5SxgDt
    XzYQtCPouzGPyOdDB68kJHgd1sOrVPcxsO6LipnQI/wPnvJLNJnMg9M7fwhRZt94
    GPrZhk4vL5TBGWZhG2k1Z9nvpdAqle0Az4ZBMpuu6FX+puPyR/kEGdTeOGgqkCsk
    L5C7c+35mfgdE1IhJA48nnVzRLlMWVxe22XXvQ9fJEkTiWJ3/4biAU3Y8W7iWAdW
    tA6AxmmKWq02YwU6ez4xtCDFnm9cGv7qmNBD0YDiuZiQeiX1UKp7LofFYvpUHQzA
    sOm4PukoZjirdRQg7qs/bqpyg8kbuxWtI0Nvolj1xu7cOik9+/EkRo7aq2Hm+gwR
    UstXVS0Mn0OV3o5w1TVawc1EUyjivgSzVfbWLZeJUd4og9XyPOkPYPUyLJdHXjYR
    6nyxyuMHzV24PMFvNp7TgYdK5Pg72PT2ru40ImIvtkE7dn4UNS0tX5bKr2mmBSKF
    6fWu2rFY8zK2VU2M4gJG5rZsqKZiP6ytnqygIHsiMKe12BgeMN+Sq7VVJsNe6fIm
    UpZQnboIsI2eaFMzDXa5V+vvNnt9smzl5JZoUM8YE4PlAi9sjyM0eK1eViFaHUmn
    oD/ONbeBqUg4rvPxf+bCu1xfL/kTc7SyPPK6CpXMPDh0CbTfuJNkdpSfGdijff4x
    ppipOcQSYIpJ4e8pkcTlkgxg6nFVOstTHzVRpPa2BFPtHlw+UZhXToF28a4u4UxV
    rKH5nq25Q0JXIYnIa00cqNKzegLRevAN+2G8EK06m0rljkajD6XxCtVUvuLNNUVO
    VpOQN5Aec0affnostOikmTJhUVx40ab6hxKQMdwqlUBJxN2HhLKlNlL6Hw5r34L0
    EM0i/0vihvqqRRjXeGmZEfUK+e+yrxUJTT9NS8wPP/IQ/iB/j63mvKdkAFrO4Wtb
    9rNPGGD30EQvx93T6kyeG7DXSCh+7ZPGlxCyZkLJnvt8K2lS3XSdVlRZLmQ2rEoU
    6UVjbo2eJAKWuWdo+SEa0/rf+VwDGZ0sGnfL60VzZyJOgQZBDZLuFFoPA9SJ9KYz
    KU1G1pb1uD2dfQk40/lA7uwPpGhXoPiGEq/TmK9guGkVW3jS0R95cO0k0OEvYiCz
    UA+aVq1aCIoLC+C24Nvr3CwBQsh910h2mPqlxAgsN530fW9ZzSaVnBqZ8XVQ8NLV
    eG7p5pgaQpvmnXT6Tt4IbAx9xYMvZrWRcpd6r03XWw8gYiDAtrle8z1x9+EjjzXi
    /oS8az59v77K47U1K9JmGU8vRKwmNo+EymHLGkHz0IxZeqF18UZWoXZRBDm1uHNi
    Vc7gbzMO/aM6HfhJ/MT+pcV8Gd3PNxovUL4wPpUbJvubcf1NMCc6+Q1Ipa3IJa7x
    SNxk7kRIbs8DtAB/krWuNY9DV0H2VMuPez5LVQJO4MJ7WS04TRdvCiKCL5tPD0uQ
    GR/Dhc4mndXblVG4UJPLhpJTIa7lIYJnyGM3p+KYKo/g04CCgM/KgNVMxEkZm1K2
    hfB2EQx7TgkaZ/Q9GA3TSy435Nkh/x1zUo7pUh7vhAsxplL+edcZSlRordojXJZG
    RcAcH6jxdHN1qQ47WJ8Z0copiewGAE3utBlbXLw1s+4UAx5s0jZr0xV1vVxZj+pT
    K5d2BJ7AVoan3ErUkwHq0Qy+yYD+sk06oNpCh6ToakxBBEqlrT0NYzYyvYfo8MYN
    qwi7PMNXlT+Ufp/4Mr31u/POJbYFJYmRWLiP4yZyMNAJ7mnyQ+6I4JZybmE+K1K1
    u7AERrkr002SfQkIQarXAGQ4FOZz0zjuQ0GpBvh1ipZfolkbdtu4olMpvJBaWZ1j
    jZsEbYTzXztBcva3D/W71WkdPHrRYNxVy7e02kwWP6+NtTxvUdFQwSS3V4ImB2Cn
    PTLiPw/Dgg/5Kgnwnu52+7KrLuSubs4SVtVTSzcWxnlfZEJE6ZYIs69d2QgEuR3J
    48xZNdh9xuecsTkyDBwxaNa7OYf4w0vqaAQpdb9+JkRnIT2jRp4bnWTuDZdeNEVG
    FM+3gmuTscA5tDm5sCWqOVqyVVgLupBrFrqkjb94OvygRROTk6mgl2jb53kwOdpy
    4I81tltDYnUhbla9s9jhmfRiozQ6peN1qn56Hy7YC45RMJ6Od5IGs59sQtHoXlbf
    enOb8uy7zsJpxVCuAeE47UAaieqyfCh8w4xXS/alvBNjcsg14FafOqIkKuudKwhV
    S3DA59X1xPJfn77yaliAI4sQWlSCrm6uJ+KA4bvu6oRTWn9x7MfKmves2r44tF7i
    Hc9QmLOJnKJErEl+CZvThKM6hORG0BSw1pqzccCrSykjALXGfygZhDRNIzt1P9+R
    Ra7E3HgfdZPVbWMQao+7oMaIWNOUdaPlN4X7dm3yWQwjPT9DESR2KgqLB9GxrfEa
    3MKpDuG1OeLjW6amXqz7gk6y0xWXZivt2qmsee8wggVsBgkqhkiG9w0BBwGgggVd
    BIIFWTCCBVUwggVRBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMw
    DgQI/XR8Q6tXxbICAggABIIEyBGjvKJc9oKUq0TdmfVvGKsq9I0Wo0oXyhJSpLH1
    E2JqXaFo92l2uu9UylLt8ui3w2dVqVtEqGxukdfR8jo5njhaZ3HfKH5JOOCWo0dL
    lVNmeQ/Ugdoug7hobPVyIEJaMr+SW9zNVuyplp2ooR65WSq4Ggkt8Iu+qxPGVJDZ
    dqYF6veViqR+8oKvW9iB73ZjgSFObVVHHJG8uM47jHvOnTCH1udga6DaJCbKsFxk
    KwSHpwoQ62Ski6DFkFS4vhW9CtpSeHxaY0Rv/BOMKXHdBf0cwcT0VsKfvioofjj/
    Qpnqk91eAeh8BG3LFO+baYufthoUJ/yJ+AhOHUy8atOzl7IpVMpGBprgVkXix06w
    buuBZ0E4a7HH/OAlZea5H6Tj9rjXzeYZMX16SoNU/KRBZ6UmlUDiVrjScad5OaEo
    H9FhZ7dtpcJB2KobmBDK/FbGHVMcwfL6A1CAay79Nd9LQe7d8x2VGy5ZEQ4PCw6q
    7OJqeAYQExHfiPBfI4yIxKV2mp4qjLrTZRfHRRbt5whwSqjj0P56dXamZjUNmjOd
    X7xnHCnrll1vC87xtRRAaGEpQQxxGfI87Y/2Gh6qgHp5n2hh2s2rI5/0cFRd6JzK
    kYsQ/Q2ScNEhuaOQjJ6pE5n4eXwp6XQmRGz8KLs7Wx9PTudsW/2lb0FHWIWMGFm5
    Q2U2Oxyzh31v1Xr8LApBXXKMTfv2aQhGOMrRwHmtBFCKPUVn1ebl22K9l+blRQyD
    0hlCsZNDS4oH7e9jd6uCbUWdjwJqIBceKFKkFUv6zBZZOPj2rZbeaaEQ5Om2SEYQ
    pjPUmjiKrWclzoLiUHiDoLIBjq80ClTGHSzzxy/eS+fjILKqARK9p3D4gJ9fkOxV
    VB26quIlGtTvABop6PJN3zvylxtkLonzQPKx+MfUjVqOswKKLxfSJuYci++hi9x0
    E3dWam5opd621tTltWXXD900N4W8a+18gU5k0yuopGhJojZcI4Ee7yhXqr76XG5F
    6Fz48mDQtNFD42NkiFpWFkSuuUGDq89O+9jXj53bTMxWp5LMQhgDhuU8l0GlkGuT
    PCa0vvCDzVTQGgX7Yl4lZlcVtNTfcNWIUG6oYVQJNUpLKlrltnDibEEoY5GWgJOI
    jCDe31dEDWCDFAjGfF1bgpbWMvtrK4O8/+k80Legmxu2STkbAonarHPBOWMfA97D
    t09ZojRTQtheYa0szXVeIWkjIHbgt23OIdfBhijPGWcdX1CqZUQzOHoMbuHF+FPv
    tQS8CRhiwfKb+l0b8D73Q+5MsT+j8bF0QagnrWLbqSBJSMAbnHA4lHyli0QyIVy9
    Ji6+ETgOYyeuU8zyIjSQ7/ba3arRcDUdP284kIrTldr4At/+5W7IHSyoKrnppSc8
    foD85JGGhbrA5WLysSKvx92JZGOijapNFjioQiGFZTlT/yDbcbENk2PC6gcgaacR
    XyafhcNOBweQONNg77dIsxuzYTSVHbs36FPSKhWkxwoVPcLIKigJQxE+Og4Fu9MR
    5TcCXncDEFNbvDf+h+8n/FVvbazowu+N5wPMAJ+nGIPgzfdohcNAc2lOYAViFk76
    W/5O3YzMyp4ENYxHmf3ye+oxicRfgvQTvNEMDVFWyp5oSQBaPLCiX1WeHDFQMCMG
    CSqGSIb3DQEJFTEWBBTygJpiyq9ZdufKfehHLmVTjipD+DApBgkqhkiG9w0BCRQx
    HB4aAGQAZQB2ADEALQBrAGEAcwBhAC0AZABlAHYwMTAhMAkGBSsOAwIaBQAEFBJK
    KOme9Y4X7XeBwuFexaKMG0xrBAhffPrliOjcugICCAA=          
