# kubectl exec -it -n sfcn-system -c asac <enforcer-pod-name> -- bash -c "echo QUIT | openssl s_client -connect <redis-host-ip>:6379 -showcerts" 
# The intermediate cert should be captured and applied into this secret value.
apiVersion: v1
kind: Secret
metadata:
  name: redisca
  namespace: sfcn-system
stringData:
  trustpoint: redisca
  value: |
    MIIFvzCCA6egAwIBAgIUZwP66OA7qRVW/u9401Q6UucjkMcwDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoLUNhcm9saW5hMRAwDgYD
    VQQHDAdSYWxlaWdoMQ4wDAYDVQQKDAVDaXNjbzERMA8GA1UECwwIU2VjdXJpdHkx
    EjAQBgNVBAMMCWNpc2NvLmNvbTAeFw0yMjA3MjUxODQ2NDRaFw0yMzA3MjUxODQ2
    NDRaMG8xCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aC1DYXJvbGluYTEQMA4G
    A1UEBwwHUmFsZWlnaDEOMAwGA1UECgwFQ2lzY28xETAPBgNVBAsMCFNlY3VyaXR5
    MRIwEAYDVQQDDAljaXNjby5jb20wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQDYP4tq6bLRlS+UORxzL0g8q9jUofGRD6BkHqZUhEE1GyyTK+mq8hqJR1AH
    edsn14tJ31VIo/1yYyY8fldYiTPls6ddX465auUD0NnSfQ684X9w8pgROzACgO96
    tMp09nZeBgL2lS+2vXxLDYyzEHytftlHfb7azzsp74Xij2I3KgwJcfX9mvRHe3WD
    CV9vmBMxdBPmihmkyO7bEXVZiHiChRCFTrOehjbHtytKt0/LbbduwQMK3MSBGkUp
    GvQD+RC8BTXQMbKEbQZni4JkF7DZ0CsHJdpHSV/tjpmeRuqXtLtT4G3EWe3zbyNr
    EWuucHbbXbvaVVgfz3MdLOEydD1DVJWywfev5HRurpHjkMBFidUssC0ITs+a4kBl
    Nfc3ruAlJlUDccINlm327JAIs/n54U7k80kRRy6cQ3piBx4QtgSAWEP2pnWEJTIj
    R5+UPJMPOlIyc9he5yId7pMRxfOIYUohBHUZzTUrmyKBDaK1n3CY0ipTizynjMYI
    rcS/YcQ0MmxIJQuPwDDz/9X0jSKfEy7CbINd3R2nL/H9Fh6MMZM2BSu+oWBEZh6i
    tkiY3n4XHYtCELZ8RnWaA8mzLT/tOKjRiyUGqSqAxiw0xkyQA124NTMKzZjuutKr
    qnKRTmTWM230OSLTUskd431XIy9tyXoNfCVI5cb6XqWBC1V2fwIDAQABo1MwUTAd
    BgNVHQ4EFgQUygc7mBZXlSj9qT5m7InwbrW6/6swHwYDVR0jBBgwFoAUygc7mBZX
    lSj9qT5m7InwbrW6/6swDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AgEAtByrFteZKFMEY9xjGxWkwK6UtfIqy7lofoAPM2yADbyd8hGPatGUXREI5nid
    dyffuNh48hbFLWvXc+qz3YN4t4Kf6pVYULTfnQNPFUHLi/NLdwhPd6CV+p0ghHYN
    nCmqCf+wv+pjjk9nsf3CZ5NJzvXuDZHcTkRTKIIsMaN7KFSKKGDBZnBNnJr3yzqm
    69yHYFx8z4Jw8VeTMaIG9DIkBe1uyiehFRd+sME3frIXBpWlVs4TqSKBPt5dJUid
    Lkh9sViExWAxN8vfMdFqkhA3ANG8ZdAiGTCpjdnV/ei/7+xuwF4uPy1S1SY7Ni28
    pzkSDEeAxpHs6TsB9h/tkpocfDOd6aoT9J7fk3guPwHxSE7skIbvyiMbYcY7WFrj
    5oMOhnAkyyN5pPz99zGn32yJtNRslBre5VWQLTIWGfJs7rMjFtgCmOnQ7N6xACgr
    SCz7EvApRaUzntM3REprn1DeI3D1Xrp2AW8Ypss98UkrDG/o1egSsRJJiPngRRxi
    YU0O8wyH1eJEWzbuC775sTU2xD5rY3tigii2AlxwdtM3CX84ZHrdh0WJWe5R/Gje
    xsrwWSr+1I9iwvO+bJlrKVwQ8T74c+DirKNF4L+Pbfyp78ZDbG+GZf/Xhdvxi/N+
    V7JGII4aiHQZXPw6N1V07Lpw2KIpwQzLaDDQ6dNUcmIeKTY=
