
# This configuration is region-specific and should match the domain
# used in the corresponding Route53Ingress spec.
# 
apiVersion: cnfw.cisco.com/v1
kind: ASAConfiguration
metadata:
  labels:
    sfcn.cisco.com/service-role: default
  name: us-enforcer-domain
  namespace: sfcn-system
spec:
  route53Ingresses:
    - enforcersUS
  order: 3
  cliLines: |
    domain-name {{ .route53Ingresses.enforcersUS.recordSetName }}
---
# This configuration is region-specific and should match the domain
# used in the corresponding Route53Ingress spec.
# 
apiVersion: cnfw.cisco.com/v1
kind: ASAConfiguration
metadata:
  labels:
    sfcn.cisco.com/service-role: vpnredirector
  name: us-redirector-domain
  namespace: sfcn-system
spec:
  route53Ingresses:
    - redirectorUS
  order: 3
  cliLines: |
    domain-name {{ .route53Ingresses.redirectorUS.recordSetName }}