apiVersion: cnfw.cisco.com/v1
kind: Route53Ingress
metadata:
  name: redirectorEU
  namespace: sfcn-system
spec:
  # Change to your Route53 hosted zone
  hostedZone: Z056XXXXXXXXXXXXXE0EK
  # Change to your VPN domain name
  recordSetName: eu.domain.com
  recordUpdate: DOMAIN
  endpointSelector:
      serviceRole: vpnredirector
---
apiVersion: cnfw.cisco.com/v1
kind: Route53Ingress
metadata:
  name: enforcersEU
  namespace: sfcn-system
spec:
  # Change to your Route53 hosted zone
  hostedZone: Z056XXXXXXXXXXXXXE0EK
  # Change to your VPN domain name
  recordSetName: eu.domain.com
  recordUpdate: SUBDOMAIN
  endpointSelector: 
    serviceRole: default
    interfaceIndex: 2
    addressType: public